from __future__ import annotations

import json
import sys
from pathlib import Path

from ai_dev_tools.models.report import Artifact, Issue, Report
from ai_dev_tools.token_efficiency import client_profile

CLIENTS = ("codex", "claude", "cursor", "generic")


def install_integrations(project_root: Path, client: str = "all", *, force: bool = False) -> Report:
    root = project_root.resolve()
    report = Report(command=f"integrations install {client}", project_root=root)
    selected = CLIENTS if client == "all" else (client,)
    if any(item not in CLIENTS for item in selected):
        report.status = "invalid_configuration"
        report.summary = {"reason_code": "UNKNOWN_INTEGRATION_CLIENT", "available": CLIENTS}
        return report

    installed: list[str] = []
    skipped: list[str] = []
    for name in selected:
        path, content = _configuration(root, name)
        if path.exists() and _already_configured(path, name):
            installed.append(path.relative_to(root).as_posix())
        elif path.exists() and not force:
            skipped.append(path.relative_to(root).as_posix())
            report.issues.append(
                Issue(
                    "warning",
                    f"Kept existing {path.relative_to(root)}; rerun with --force to replace it",
                    code="INTEGRATION_CONFIG_EXISTS",
                )
            )
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            if path.exists() and force:
                content = _merge_existing(path, content, name)
            path.write_text(content, encoding="utf-8")
            installed.append(path.relative_to(root).as_posix())
            report.artifacts.append(
                Artifact(str(path), "integration-config", f"Ready-to-use {name} MCP configuration")
            )
        profile_path = root / ".ai-dev" / "clients" / f"{name}.json"
        if force or not profile_path.exists():
            profile_path.parent.mkdir(parents=True, exist_ok=True)
            profile_path.write_text(
                json.dumps(
                    {"schema_version": "1", "client": name, **client_profile(name)},
                    indent=2,
                    sort_keys=True,
                )
                + "\n",
                encoding="utf-8",
            )
        installed.append(profile_path.relative_to(root).as_posix())
        report.artifacts.append(
            Artifact(
                str(profile_path),
                "client-profile",
                f"Token-efficient {name} task preparation defaults",
            )
        )
    report.status = "partial" if skipped else "success"
    report.summary = {
        "installed": installed,
        "skipped": skipped,
        "clients": list(selected),
        "transport": "stdio",
    }
    return report


def _configuration(root: Path, client: str) -> tuple[Path, str]:
    command = [sys.executable, "-m", "ai_dev_tools", "--project", str(root), "mcp", "serve"]
    if client == "codex":
        quoted = ", ".join(json.dumps(value) for value in command[1:])
        content = (
            "# Generated by ai-dev integrations install codex\n"
            "[mcp_servers.ai-dev-tools]\n"
            f"command = {json.dumps(command[0])}\n"
            f"args = [{quoted}]\n"
            "startup_timeout_sec = 15\n"
            "tool_timeout_sec = 300\n"
        )
        return root / ".codex" / "config.toml", content
    payload = {
        "mcpServers": {
            "ai-dev-tools": {
                "command": command[0],
                "args": command[1:],
            }
        }
    }
    paths = {
        "claude": root / ".mcp.json",
        "cursor": root / ".cursor" / "mcp.json",
        "generic": root / "mcp.ai-dev.json",
    }
    return paths[client], json.dumps(payload, indent=2) + "\n"


def _already_configured(path: Path, client: str) -> bool:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return False
    if client == "codex":
        return "[mcp_servers.ai-dev-tools]" in text
    try:
        payload = json.loads(text)
    except json.JSONDecodeError:
        return False
    return isinstance(payload, dict) and "ai-dev-tools" in payload.get("mcpServers", {})


def _merge_existing(path: Path, generated: str, client: str) -> str:
    existing = path.read_text(encoding="utf-8")
    if client == "codex":
        return existing.rstrip() + "\n\n" + generated
    try:
        current = json.loads(existing)
        addition = json.loads(generated)
    except json.JSONDecodeError:
        return generated
    if not isinstance(current, dict):
        return generated
    servers = current.setdefault("mcpServers", {})
    if not isinstance(servers, dict):
        current["mcpServers"] = {}
        servers = current["mcpServers"]
    servers["ai-dev-tools"] = addition["mcpServers"]["ai-dev-tools"]
    return json.dumps(current, indent=2) + "\n"
